name: 'benchmark'
description: 'benchmark your codebase continuously'
inputs:
  token:
    description: 'The GitHub token to use'
    required: true
  main_branch:
    description: 'The main branch of the repository. Will be used to compare data against.'
    required: true
  artifact_name:
    description: 'The name of the artifact to upload'
    required: false
  max_commits_to_traverse:
    description: 'The maximum number of commits to traverse when searching for artifacts'
    required: false
    default: '20'
  key:
    description: 'the key to use for the benchmark'
  value:
    description: 'the value for the benchmark'
outputs:
  downloaded_artifacts:
    description: data that was stored in the main branch
runs:
  using: 'node16'
  main: 'dist/index.js'
