name: 'benchmark'
description: 'benchmark your codebase continuously'
inputs:
  token:
    description: 'The GitHub token to use'
    required: true
  main_branch:
    description: 'The main branch of the repository. Will be used to compare data against.'
    required: true
  artifact_name:
    description: 'The name of the artifact to upload'
    required: false
  max_commits_to_traverse:
    description: 'The maximum number of commits to traverse when searching for artifacts'
    required: false
    default: '20'
  should_comment:
    description: 'Whether or not to comment on the PR'

  # one of [key,value], [json], or [input_file] must be provided
  key:
    description: 'the key to use for the benchmark'
  value:
    description: 'the value for the benchmark'
  json:
    description: 'A json for an array of metrics'
  input_file:
    description: 'A file containing a json for an array of metrics'

outputs:
  downloaded_artifacts:
    description: data that was stored in the main branch
runs:
  using: 'node16'
  main: 'dist/index.js'
